version: "3"

services:
  client:
    # image: client_v1
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start

  server:
    # image: server_v1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # command: npm run start
    command: npm run debug
